"""create maintanace event model

Revision ID: 57898188e7e9
Revises: 858192e7d1d1
Create Date: 2021-12-13 09:56:43.565857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57898188e7e9'
down_revision = '858192e7d1d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'phone')
    op.drop_column('home_owner', 'phone')
    op.drop_column('home_owner_manager', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home_owner_manager', sa.Column('phone', sa.VARCHAR(length=13), autoincrement=False, nullable=False))
    op.add_column('home_owner', sa.Column('phone', sa.VARCHAR(length=13), autoincrement=False, nullable=False))
    op.add_column('admins', sa.Column('phone', sa.VARCHAR(length=13), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
