"""update table maint_event

Revision ID: 764bd1364b10
Revises: f5e1515692cb
Create Date: 2021-12-16 13:44:48.901934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764bd1364b10'
down_revision = 'f5e1515692cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='state'), nullable=False),
    sa.Column('home_owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['home_owner_id'], ['home_owner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('home_owner', 'bank_details',
               existing_type=sa.VARCHAR(length=22),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('home_owner', 'bank_details',
               existing_type=sa.VARCHAR(length=22),
               nullable=True)
    op.drop_table('maintenance_event')
    # ### end Alembic commands ###
