"""add bank_details for home_owner_managers

Revision ID: ce7304f169eb
Revises: 4c1235b02aff
Create Date: 2021-12-18 16:31:15.349178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce7304f169eb'
down_revision = '4c1235b02aff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home_owner_manager', sa.Column('bank_details', sa.String(length=16), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('home_owner_manager', 'bank_details')
    # ### end Alembic commands ###
