"""empty message

Revision ID: d7709e205b2a
Revises: fe258973cdb0
Create Date: 2021-12-17 17:42:07.219823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7709e205b2a'
down_revision = 'fe258973cdb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='state'), nullable=False),
    sa.Column('home_owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['home_owner_id'], ['home_owner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('admins', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('admins', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('home_owner', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('home_owner', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.alter_column('home_owner', 'bank_details',
               existing_type=sa.VARCHAR(length=22),
               type_=sa.String(length=16),
               nullable=False)
    op.add_column('home_owner_manager', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('home_owner_manager', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_on')
    op.drop_column('users', 'created_on')
    op.drop_column('home_owner_manager', 'updated_on')
    op.drop_column('home_owner_manager', 'created_on')
    op.alter_column('home_owner', 'bank_details',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=22),
               nullable=True)
    op.drop_column('home_owner', 'updated_on')
    op.drop_column('home_owner', 'created_on')
    op.drop_column('admins', 'updated_on')
    op.drop_column('admins', 'created_on')
    op.drop_table('maintenance_event')
    # ### end Alembic commands ###
